INSERT INTO bieblo.tag (name, description, settings) VALUES ('Grappige verhalen', '', '{}');
INSERT INTO bieblo.tag (name, description, settings) VALUES ('Fantasieverhalen', null, '{}');
INSERT INTO bieblo.tag (name, description, settings) VALUES ('Spannende verhalens', null, '{}');
INSERT INTO bieblo.tag (name, description, settings) VALUES ('Sportverhalen', null, '{}');
INSERT INTO bieblo.tag (name, description, settings) VALUES ('Dieren', null, '{}');
INSERT INTO bieblo.tag (name, description, settings) VALUES ('Andere landen', null, '{}');
INSERT INTO bieblo.tag (name, description, settings) VALUES ('Liefdesverhalen', null, '{}');
INSERT INTO bieblo.tag (name, description, settings) VALUES ('Historische verhalen', null, '{}');
INSERT INTO bieblo.tag (name, description, settings) VALUES ('Prijsboeken', null, '{}');
INSERT INTO bieblo.tag (name, description, settings) VALUES ('Vriendschap', null, '{}');