<?php

namespace AppBundle\Repository;

/**
 * AgeGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgeGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
