<?php

namespace AppBundle\Repository;

/**
 * BookTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookTagRepository extends \Doctrine\ORM\EntityRepository
{
}
