# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
    app.cc.language: nl
    app.cc.root.api.version: v0
    app.cc.gent.api.version: v0
    app.cc.root.domain: zoeken.bibliotheek.be
    app.cc.gent.domain: zoeken.ninove.bibliotheek.be
    app.regions.entityRepository: "AppBundle:Region"
    app.libraries.entityRepository: "AppBundle:Library"
    app.books.entityRepository: "AppBundle:Book"
    app.keywords.entityRepository: "AppBundle:Keyword"
    app.ageGroups.entityRepository: "AppBundle:AgeGroup"
    app.tags.entityRepository: "AppBundle:Tag"
    app.bookTags.entityRepository: "AppBundle:BookTag"

services:
    app.cc.server.root:
        class: AppBundle\Service\CultuurConnect\Server
        arguments: ['%app.cc.root.domain%', '%app.cc.root.authorization%', '%app.cc.root.api.version%', '%app.cc.language%']
    app.cc.server.gent:
        class: AppBundle\Service\CultuurConnect\Server
        arguments: ['%app.cc.gent.domain%', '%app.cc.gent.authorization%', '%app.cc.gent.api.version%', '%app.cc.language%']
    app.cc.fetch.regions:
        class: AppBundle\Service\CultuurConnect\Fetch\Regions
        arguments: ['@app.cc.server.root', '@doctrine.orm.entity_manager', '%app.regions.entityRepository%']
    app.cc.fetch.libraries:
        class: AppBundle\Service\CultuurConnect\Fetch\Libraries
        arguments: ['@app.cc.server.root', '@doctrine.orm.entity_manager', '%app.libraries.entityRepository%']
    app.cc.fetch.books:
        class: AppBundle\Service\CultuurConnect\Fetch\Books
        arguments: ['@app.cc.server.gent', '@doctrine.orm.entity_manager', '%app.books.entityRepository%']
    app.cc.fetch.availability:
        class: AppBundle\Service\CultuurConnect\Fetch\Availability
        arguments: ['@app.cc.server.gent', '@doctrine.orm.entity_manager', '%app.books.entityRepository%']
    app.bieblo.fetch.regions:
        class: AppBundle\Service\Bieblo\Fetch\RegionsFetchService
        arguments: ['@doctrine.orm.entity_manager', '%app.regions.entityRepository%']
    app.bieblo.fetch.libraries:
        class: AppBundle\Service\Bieblo\Fetch\LibrariesFetchService
        arguments: ['@doctrine.orm.entity_manager', '%app.libraries.entityRepository%']
    app.bieblo.fetch.keywords:
        class: AppBundle\Service\Bieblo\Fetch\KeywordsFetchService
        arguments: ['@doctrine.orm.entity_manager', '%app.keywords.entityRepository%']
    app.bieblo.fetch.ageGroups:
        class: AppBundle\Service\Bieblo\Fetch\AgeGroupsFetchService
        arguments: ['@doctrine.orm.entity_manager', '%app.ageGroups.entityRepository%']
    app.bieblo.fetch.tags:
        class: AppBundle\Service\Bieblo\Fetch\TagsFetchService
        arguments: ['@doctrine.orm.entity_manager', '%app.tags.entityRepository%']
    app.bieblo.fetch.bookTags:
        class: AppBundle\Service\Bieblo\Fetch\BookTagsFetchService
        arguments: ['@doctrine.orm.entity_manager', '%app.bookTags.entityRepository%']
    app.bieblo.fetch.books:
        class: AppBundle\Service\Bieblo\Fetch\BooksFetchService
        arguments: ['@doctrine.orm.entity_manager', '%app.books.entityRepository%']
    app.bieblo.entity.keyword:
        class: AppBundle\Service\Bieblo\Entity\KeywordEntityService
        arguments: ['@doctrine.orm.entity_manager', '%app.ageGroups.entityRepository%']
    app.bieblo.sync.regions:
        class: AppBundle\Service\Bieblo\Sync\Regions
        arguments: ['@doctrine.orm.entity_manager', '@monolog.logger.sync', '@app.cc.fetch.regions']
    app.bieblo.sync.libraries:
        class: AppBundle\Service\Bieblo\Sync\Libraries
        arguments: ['@doctrine.orm.entity_manager', '@monolog.logger.sync', '@app.bieblo.fetch.regions', '@app.cc.fetch.libraries']
    app.bieblo.sync.books:
        class: AppBundle\Service\Bieblo\Sync\Books
        arguments: ['@doctrine.orm.entity_manager', '@monolog.logger.sync', '@app.cc.fetch.books']
