<?php
namespace AppBundle\StaticData;

class Queries {
    static public function getTags() {
        return [
            1 => [
                '(genre:humor OR subject:lachen) AND subject:schoolleven',
                '(genre:humor OR subject:lachen) AND subject:heksen',
                '(genre:humor OR subject:lachen) AND subject:chicklit',
                '(genre:humor OR subject:lachen) AND subject:magie',
                '(genre:humor OR subject:lachen) AND subject:vriendschap',
                '(genre:humor OR subject:lachen) AND subject:"anders zijn"',
                '(genre:humor OR subject:lachen) AND subject:"verliefd zijn"',
                '(genre:humor OR subject:lachen) AND subject:grootouders',
                '(genre:humor OR subject:lachen) AND subject:gezin',
                '(genre:humor OR subject:lachen) AND subject:helden',
                '(genre:humor OR subject:lachen) AND subject:"broers en zussen"',
                '(genre:humor OR subject:lachen) AND subject:spoken',
                '(genre:humor OR subject:lachen) AND subject:vakantie',
            ],
            2 => [
                '(genre:fantasieverhalen)',
                '(subject:fantaseren)' ,
                '(subject:heksen)',
                '(subject:"prinsen en prinsessen")',
                '(subject:toveren)',
                '(subject:draken)',
                '(subject:griezels)',
                '(subject:zeerovers)',
                '(subject:fantasievriendjes)',
            ],
            3 => [
                '(genre:"detectives")', '(genre:"avonturenverhalen")', '(genre:"griezelverhalen")',
                '(subject:diefstallen)', '(subject:spioneren)', '(subject:mysteries)',
                '(subject:geheimen)', '(subject:misdaad)', '(subject:”gijzelingen en ontvoeringen”)',
                '(subject:detectives)',
            ],
            4 => [
                '(genre:sportverhalen)',
                '(subject:voetbal)',
                '(subject:sport)',
                '(subject:autosport',
                '(subject:zwemmen)',
                '(subject:bergsport)',
                '(subject:wedstrijden)',
                '(subject:jockey)',
                '(subject:"winnen verliezen")',
                '(subject:skateboarden)',
                '(subject:snowboarden)',
                '(subject:motorsport)',
                '(subject:basketbal)',
            ],
            5 => [
                '(subject:"vriendschap met dieren ")', '(subject:dieren)', '(subject:honden)', '(subject:katten)',
                '(subject:paarden)', '(subject:dierenbescherming)', '(subject:dierenartsen)', '(subject:boerderijen)',
                '(subject:huisdieren)',
            ],
            6 => [
                '(subject:”andere culturen”)', '(subject:vluchtelingen)', '(subject:volken)',
                '(subject:indianen)', '(subject:”multiculturele samenleving”)',
            ],
            7 => [
                '(genre:liefdesverhalen)',
                'subject:liefde',
                'subject:vriendschap',
                'subject:"verliefd zijn"',
                'subject:"eenzaam zijn"',
                'subject:"afscheid nemen"',
                'subject:puberteit',
                'subject:seksualiteit',
            ],
            8 => [
                'genre:”historische verhalen”',
                'genre:oorlogsverhalen',
                'subject:middeleeuwen',
                'subject:ridders',
                'subject:oertijd',
                'subject:kinderarbeid',
                'subject:geschiedenis',
                'subject:"16de, 17de, 20ste eeuw"',
                'subject:tijdrijzen',
                'subject:"romeinse rijk"',
                'subject:overleven',
            ],
            9 => [
                'awards:boekenleeuw',
                'awards:boekenpauw',
                'awards:"zilveren griffel"',
                'awards:"zilveren penseel"',
                'awards:"gouden penseel"',
                'awards:"gouden uil"',
                'awards:"wouterse pieterse prijs"',
                'awards:KJV',
                'awards:"nederlands kinderjury"',
            ],
            10 => [
                'subject:vriendschap',
                'subject:"vriendschap met dieren"',
                'subject:"anders zijn"',
                'subject:schoolleven',
                'subject:geheimen',
                'subject:pesten',
                'subject:"jaloers zijn"',
                'subject:grootouders',
                'subject:gezin',
            ],
        ];
    }
}
