<?php

namespace AppBundle\Repository\Tag;

/**
 * QueryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QueryRepository extends \Doctrine\ORM\EntityRepository
{
}
